import { writeFile } from "node:fs/promises";
import type { Catalog, Issue } from "../src/data/build-catalog.ts";

const target = new URL("../src/catalog.ts", import.meta.url);

export async function writeCatalogFile(catalog: Catalog) {
  await writeFile(
    target,
    `// Generated by scripts/pull-catalog.ts from Supabase. Do not edit by hand.\nexport const catalog = ${JSON.stringify(catalog, null, 2)};\n`,
  );
}

export function failOnIssues(issues: Issue[]) {
  if (!issues.length) return;
  console.error(`데이터 검증 실패 (${issues.length}건):`);
  for (const issue of issues) console.error(`- ${issue.message}`);
  process.exit(1);
}

export const summary = (catalog: Catalog) =>
  `곡 ${catalog.songs.length} · 문제 ${catalog.questions.length} · 영어 사전 ${catalog.dictionary.length}`;
