import {create} from 'zustand';
import {persist} from 'zustand/middleware';
import {allKeys, matches, normalize, titleMatches, pickQuestion, progress, questions, units} from './game.ts';
type Stats={solved:number;completed:number;direct:number;skipped:number;streak:number;best:number};
type Round={id:string;revealed:string[];words:{word:string;hit:boolean}[];solved:boolean;givenUp:boolean;english:boolean;hints:number;wordHints:number;counted:boolean};
const newRound=(id:string):Round=>({id,revealed:[],words:[],solved:false,givenUp:false,english:false,hints:0,wordHints:0,counted:false});
const emptyStats=():Stats=>({solved:0,completed:0,direct:0,skipped:0,streak:0,best:0});
const complete=(round:Round,stats:Stats)=>{const q=questions.find(q=>q.id===round.id)!;const p=progress(q,round.revealed); if(p.count===p.total&&!round.counted&&!round.givenUp){round.counted=true;stats.completed++;if(!round.wordHints)stats.direct++;}};
type Store={selected:string[];seen:string[];round:Round;stats:Stats;notice:string;guess:(word:string)=>void;solve:(title:string)=>boolean;hint:(type:'english'|'word')=>void;giveUp:()=>void;next:()=>void;select:(selected:string[])=>void;reset:()=>void};
const firstQuestion=pickQuestion(units,[]);
export const useGame=create<Store>()(persist((set,get)=>({
 selected:units,seen:[firstQuestion.id],round:newRound(firstQuestion.id),stats:emptyStats(),notice:'',
 guess:(word)=>{const s=get();if(s.round.givenUp)return;const text=word.trim().slice(0,60);if(!text)return;const found=matches(questions.find(q=>q.id===s.round.id)!,text,s.round.revealed);const added=found.filter(k=>!s.round.revealed.includes(k));if(!added.length&&s.round.words.some(w=>normalize(w.word)===normalize(text))){set({notice:'이미 찾아본 단어예요. 새로 열리는 부분이 없어요.'});return;}const round={...s.round,revealed:[...new Set([...s.round.revealed,...found])],words:[...s.round.words,{word:text,hit:found.length>0}]};const stats={...s.stats};complete(round,stats);set({round,stats,notice:added.length?'좋아요! 숨겨진 가사를 찾았어요.':found.length?'이미 공개된 가사예요.':'이 구간에는 없는 단어예요. 다시 도전해 봐요.'});},
 solve:(title)=>{const s=get();if(s.round.solved||s.round.givenUp)return false;const q=questions.find(q=>q.id===s.round.id)!;if(!titleMatches(q,title)){set({notice:'아직 정답이 아니에요. 가사를 조금 더 채워 보세요.'});return false;}const streak=s.stats.streak+1;set({round:{...s.round,solved:true},stats:{...s.stats,solved:s.stats.solved+1,streak,best:Math.max(streak,s.stats.best)},notice:'제목 정답! 남은 가사도 계속 채울 수 있어요.'});return true;},
 hint:(type)=>{const s=get();if(s.round.givenUp)return;const round={...s.round,revealed:[...s.round.revealed]};if(type==='english'){if(round.english)return;round.english=true;}else{const q=questions.find(q=>q.id===round.id)!;const hidden=allKeys(q).find(k=>!round.revealed.includes(k));if(!hidden)return;const prefix=hidden.split(':').slice(0,2).join(':')+':';round.revealed=[...new Set([...round.revealed,...allKeys(q).filter(k=>k.startsWith(prefix))])];round.wordHints++;}round.hints++;const stats={...s.stats};complete(round,stats);set({round,stats,notice:type==='english'?'영어 부분에 보라색 밑줄을 표시했어요.':'숨겨진 단어 하나를 공개했어요.'});},
 giveUp:()=>{const s=get();if(s.round.givenUp||s.round.solved)return;set({round:{...s.round,givenUp:true},stats:{...s.stats,skipped:s.stats.skipped+1,streak:0},notice:'괜찮아요. 다음 노래에서 다시 만나요.'});},
 next:()=>{const s=get();if(!s.round.solved&&!s.round.givenUp)return;const q=pickQuestion(s.selected,s.seen,s.round.id);const pool=questions.filter(q=>s.selected.includes(q.unit));const seen=pool.every(q=>s.seen.includes(q.id))?[q.id]:[...s.seen,q.id];set({round:newRound(q.id),seen,notice:''});},
 select:(selected)=>{if(selected.length)set({selected,notice:'선택한 범위는 다음 문제부터 적용돼요.'});},
 reset:()=>{const q=pickQuestion(units,[]);set({stats:emptyStats(),round:newRound(q.id),selected:units,seen:[q.id],notice:'기록을 초기화했어요.'});}
}),{name:'chosung-lyrics-live-v1',version:1,partialize:({notice,...s})=>s,merge:(persisted,current)=>{const p=persisted as Partial<Store>|undefined;if(!p||!p.round||!questions.some(q=>q.id===p.round?.id))return current;const selected=Array.isArray(p.selected)?p.selected.filter(u=>units.includes(u)):units;return {...current,...p,selected:selected.length?selected:units,notice:''};}}));
